# Generated by Django 3.0.7 on 2020-06-17 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=50, unique=True)),
                ('nacionalidad', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro', models.CharField(max_length=50)),
                ('editorial', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('fechaHora_registro', models.DateTimeField(auto_now_add=True)),
                ('idAutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Autor')),
            ],
            options={
                'unique_together': {('libro', 'autor')},
            },
        ),
    ]
